/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://mnknujn5ybb3bodox55sykedzy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dx5qfaqwfjdlph52q74ipn6dby",
    "aws_cognito_identity_pool_id": "us-east-1:5d3a4c03-1ba4-462e-aecf-e6b1bfd87571",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8vlMeBve4",
    "aws_user_pools_web_client_id": "3mp99ce70v9ntfj7p2u8pka7c1",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
